"""modify class ShopAds

Revision ID: 0017e0e4bb52
Revises: 753407bfcfa9
Create Date: 2023-04-19 17:16:41.954653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0017e0e4bb52'
down_revision = '753407bfcfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menuAdID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shop_ads_ad_id_fkey', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shop_ads_shop_menu_id_fkey', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop_menus', ['shop_ads_shop_menu_id_fkey'], ['shopMenuID'])
        batch_op.create_foreign_key(None, 'advertisements', ['shop_ads_ad_id_fkey'], ['adID'])
        batch_op.drop_column('adID')
        batch_op.drop_column('shopID')
        batch_op.drop_column('displayID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displayID', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('shopID', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('adID', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shopID'], ['shopID'])
        batch_op.create_foreign_key(None, 'advertisements', ['adID'], ['adID'])
        batch_op.create_foreign_key(None, 'displays', ['displayID'], ['displayID'])
        batch_op.drop_column('shop_ads_shop_menu_id_fkey')
        batch_op.drop_column('shop_ads_ad_id_fkey')
        batch_op.drop_column('menuAdID')

    # ### end Alembic commands ###
