"""ad order and shop display of ads

Revision ID: 32936521c07b
Revises: fecb5af4da71
Create Date: 2023-04-19 16:06:18.347200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32936521c07b'
down_revision = 'fecb5af4da71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adOrder', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_ads', schema=None) as batch_op:
        batch_op.drop_column('adOrder')

    # ### end Alembic commands ###
