"""New Migration

Revision ID: 4185b4befbfd
Revises: 2b918c824530
Create Date: 2023-04-09 17:03:45.418567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4185b4befbfd'
down_revision = '2b918c824530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###
