"""empty message

Revision ID: 6107f2ed9d48
Revises: 
Create Date: 2023-03-19 15:01:23.601996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6107f2ed9d48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopMenuID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('menuTypeID', sa.Integer(), nullable=True))
        batch_op.alter_column('displayID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'menus', ['menuTypeID'], ['menuID'])
        batch_op.drop_column('menuID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menuID', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'menus', ['menuID'], ['menuID'])
        batch_op.alter_column('displayID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('menuTypeID')
        batch_op.drop_column('shopMenuID')

    # ### end Alembic commands ###
