"""New Migration

Revision ID: 7d96ebd19353
Revises: ef106dda8f6f
Create Date: 2023-04-09 16:08:52.282166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d96ebd19353'
down_revision = 'ef106dda8f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adFilePath', sa.String(length=200), nullable=False))
        batch_op.drop_column('adGraphic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adGraphic', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('adFilePath')

    # ### end Alembic commands ###
