"""Database mode for interchangable menus

Revision ID: 91978ad7c338
Revises: 91ad0807c751
Create Date: 2023-04-15 14:16:37.709079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91978ad7c338'
down_revision = '91ad0807c751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('displayID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displayID', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'displays', ['displayID'], ['displayID'])

    # ### end Alembic commands ###
