"""Database mode for interchangable menus

Revision ID: 97e191f0dd2d
Revises: c26c351cb9cb
Create Date: 2023-04-15 13:53:24.704339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e191f0dd2d'
down_revision = 'c26c351cb9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display_menu',
    sa.Column('displayMenuID', sa.Integer(), nullable=False),
    sa.Column('displayID', sa.Integer(), nullable=True),
    sa.Column('shopMenuID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['displayID'], ['displays.displayID'], ),
    sa.ForeignKeyConstraint(['shopMenuID'], ['menus.menuID'], ),
    sa.PrimaryKeyConstraint('displayMenuID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('display_menu')
    # ### end Alembic commands ###
