"""modify class ShopAds

Revision ID: c93452582a3a
Revises: 0017e0e4bb52
Create Date: 2023-04-19 17:33:02.842715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93452582a3a'
down_revision = '0017e0e4bb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menuAdID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('menuID', sa.Integer(), nullable=True))
        batch_op.alter_column('adID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'shop_menus', ['menuID'], ['shopMenuID'])
        batch_op.drop_column('shopID')
        batch_op.drop_column('displayID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displayID', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('shopID', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'shops', ['shopID'], ['shopID'])
        batch_op.create_foreign_key(None, 'displays', ['displayID'], ['displayID'])
        batch_op.alter_column('adID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('menuID')
        batch_op.drop_column('menuAdID')

    # ### end Alembic commands ###
