"""New Migration

Revision ID: ef106dda8f6f
Revises: 6107f2ed9d48
Create Date: 2023-04-09 11:03:46.131603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef106dda8f6f'
down_revision = '6107f2ed9d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemSubitem', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('itemSubitem')

    # ### end Alembic commands ###
