"""New Migration

Revision ID: f23c00727037
Revises: 4185b4befbfd
Create Date: 2023-04-10 00:15:28.613164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23c00727037'
down_revision = '4185b4befbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primaryUserID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['primaryUserID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('primaryUserID')

    # ### end Alembic commands ###
